version: '3.8'

services:
  webapp:
    container_name: react_webapp
    image: victoryeo00/server:latest
    ports:
      - "3001:3000"
    volumes:
      - ./ReactJS:/app
  orders:
    container_name: orders_backend
    restart: always
    image: victoryeo00/order_backend:latest
    ports:
      - "9091:9090"
